In [1]:
# ライブラリの読み込み
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets

# データの読み込み
iris_datasets = datasets.load_iris()
iris = pd.DataFrame(iris_datasets.data,columns=iris_datasets.feature_names)
iris['target']=iris_datasets.target
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [2]:
# irisデータを目的変数(taeget)と説明変数(data)に分ける
# shift + Enter で，ln[]を実行できる
target=iris['target']
data=iris[iris_datasets.feature_names]

In [3]:
# train_test_splitで，学習データと検証データに分割
# OS Windowsでのバックスラッシュの入力は，半角設定にした，キーボードのろをタイプすればよい
from sklearn import model_selection
data_train, data_test, target_train, target_test=\
    model_selection.train_test_split(data,target,train_size=0.8)

In [4]:
# shift + Enter で，ln[]を実行できる
print(target_train.shape,target_test.shape)
print(data_train.shape, data_test.shape)

(120,) (30,)
(120, 4) (30, 4)


In [5]:
# ライブラリの読み込み
from sklearn.svm import SVC
# モデルの初期化
model = SVC(gamma='scale')
# 学習の実施
model.fit(data_train, target_train)

# 実行結果：SVC()のみの表示-->問題なし

SVC()

In [6]:
target_predict = model.predict(data_test)

In [7]:
# 実行結果：テキスト p.159 と同じではなくてもよい．
# 生成されるデータが使用するPCごとに異なるため
print(target_predict)
print(np.array(target_test))

[0 1 2 0 0 1 1 1 1 0 0 0 1 2 1 2 1 1 0 1 1 0 2 2 0 0 1 2 1 0]
[0 1 2 0 0 1 1 1 1 0 0 0 1 2 1 2 1 1 0 1 1 0 2 2 0 0 1 2 1 0]


In [8]:
# 正答率
# 実行結果：テキスト p.159 と同じではなくてもよい．
# 生成されるデータが使用するPCごとに異なるため
model.score(data_test, target_test)

1.0

In [10]:
# ライブラリの読み込み
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score

# 各値の取得
precision = precision_score(target_test, target_predict, average='micro')
recall = recall_score(target_test, target_predict, average='micro')
f1=f1_score(target_test, target_predict, average='micro')

# 各値の表示
print('適合率(precision):', precision)
print('再現率(recall):', recall)
print('F値(F-meacure):', f1)

適合率(precision): 1.0
再現率(recall): 1.0
F値(F-meacure): 1.0


In [11]:
# ライブラリの読み込み
from sklearn.linear_model import LogisticRegression
# モデルの初期化
model = LogisticRegression(solver='lbfgs', multi_class='auto')
# 学習の実施
model.fit(data_train, target_train)

# 予測
target_predict = model.predict(data_test)
print(target_predict)
print(np.array(target_test))

# 正解率の表示
model.score(data_test, target_test)

[0 1 2 0 0 1 1 1 1 0 0 0 1 2 1 2 1 1 0 1 1 0 2 2 0 0 1 2 1 0]
[0 1 2 0 0 1 1 1 1 0 0 0 1 2 1 2 1 1 0 1 1 0 2 2 0 0 1 2 1 0]


1.0

In [12]:
# 決定木
# ライブラリの読み込み
from sklearn.tree import DecisionTreeClassifier
# モデルの初期化
model = DecisionTreeClassifier()

In [13]:
# ランダムフォレスト
from sklearn.ensemble import RandomForestClassifier
# モデルの初期化
model = RandomForestClassifier(n_estimators=100)

In [14]:
# パーセプトロン
# ライブラリの読み込み
from sklearn.linear_model import Perceptron
# モデルの初期化
model = Perceptron()